### ISSUE TITLE
Problem with running examples due to mrjob

### ISSUE THREAD

**Issue by krunkfoo** [YelpArchive/dataset-examples#6] opened 2014-04-03 00:44 UTC
Im trying to run these examples in windows and I get a vague error that says that there is something wrong with invoke sort. 

 File "F:/Yelp/dataset-examples-master/review_autopilot/autopilot.py", line 151, in <module>
    ReviewAutoPilot().run()
  File "C:\Python27\lib\site-packages\mrjob\job.py", line 494, in run
    mr_job.execute()
  File "C:\Python27\lib\site-packages\mrjob\job.py", line 512, in execute
    super(MRJob, self).execute()
  File "C:\Python27\lib\site-packages\mrjob\launch.py", line 147, in execute
    self.run_job()
  File "C:\Python27\lib\site-packages\mrjob\launch.py", line 208, in run_job
    runner.run()
  File "C:\Python27\lib\site-packages\mrjob\runner.py", line 458, in run
    self._run()
  File "C:\Python27\lib\site-packages\mrjob\sim.py", line 191, in _run
    self._invoke_sort(self._step_input_paths(), sort_output_path)
  File "C:\Python27\lib\site-packages\mrjob\runner.py", line 1225, in _invoke_sort
    proc.stdin.write(buf)
IOError: [Errno 22] Invalid argument

**Comment by sc932** [comment] 2014-04-22 23:28
What command did you run to generate this error? I am having trouble reproducing this.

Have you tried this in OSX or linux?

**Comment by krunkfoo** [comment] 2014-04-23 20:20
review_autopilot/autopilot.py yelp_academic_dataset.json > autopilot.json 

No I havent tried running this on OSX or linux.

**Comment by sc932** [comment] 2014-04-24 23:48
I think this is an mrjob issue and not an issue with the dataset-examples. It looks like it is failing before it even gets to the code in this repo.

I couldn't find this issue at https://github.com/Yelp/mrjob/issues, I would suggest posting it there.

I did find this link: http://machinelearningbigdata.pbworks.com/w/page/39028853/mrjob%20installation
maybe installing setuptools will help?

I am going to close this issue for now since I don't think it is related to this repo. Long term I would highly recommend getting a linux/*nix VM to develop in, many open source projects implicitly require it.

**Closed as completed by sc932** 2014-04-24 23:48 UTC
